{{- if .Values.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatapp.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.openai.apiKey | quote }}
{{- end }}
