apiVersion: v1
kind: Service
metadata:
  name: messages
  namespace: {{ .Values.namespace }}
  labels:
{{ include "chatapp.labels" . | indent 4 }}
    app.kubernetes.io/component: messages
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: messages
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
      name: http
