{{- if .Values.irsa.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.irsa.serviceAccount }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "chatapp.labels" . | indent 4 }}
  {{- if .Values.irsa.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn | quote }}
  {{- end }}
{{- end }}
